version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8080:8080 #80:8080 not display port
    command: python manage.py runserver 0.0.0.0:8080
    #    command: >
    #      sh -c "python manage.py runserver aibi.vn:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=hospital
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=hospital
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #    volumes:
    #      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432




